const fileImgMap = {
  folder: require("@/assets/images/file/dir.png"),
  avi: require("@/assets/images/file/file_avi.png"),
  jar: require("@/assets/images/file/file_jar.png"),
  c: require("@/assets/images/file/file_c.png"),
  chm: require("@/assets/images/file/file_chm.png"),
  css: require("@/assets/images/file/file_css.png"),
  csv: require("@/assets/images/file/file_csv.png"),
  dmg: require("@/assets/images/file/file_dmg.png"),
  go: require("@/assets/images/file/file_go.png"),
  java: require("@/assets/images/file/file_java.png"),
  js: require("@/assets/images/file/file_js.png"),
  jsp: require("@/assets/images/file/file_jsp.png"),
  kotlin: require("@/assets/images/file/file_kotlin.png"),
  less: require("@/assets/images/file/file_less.png"),
  lua: require("@/assets/images/file/file_lua.png"),
  markdown: require("@/assets/images/file/file_markdown.png"),
  music: require("@/assets/images/file/file_music.png"),
  nginx: require("@/assets/images/file/file_nginx.png"),
  oa: require("@/assets/images/file/file_oa.png"),
  open: require("@/assets/images/file/file_open.png"),
  php: require("@/assets/images/file/file_php.png"),
  powershell: require("@/assets/images/file/file_powershell.png"),
  properties: require("@/assets/images/file/file_properties.png"),
  python: require("@/assets/images/file/file_python.png"),
  r: require("@/assets/images/file/file_r.png"),
  rar: require("@/assets/images/file/file_rar.png"),
  rtf: require("@/assets/images/file/file_rtf.png"),
  rust: require("@/assets/images/file/file_rust.png"),
  sass: require("@/assets/images/file/file_sass.png"),
  scss: require("@/assets/images/file/file_scss.png"),
  shell: require("@/assets/images/file/file_shell.png"),
  sql: require("@/assets/images/file/file_sql.png"),
  stylus: require("@/assets/images/file/file_stylus.png"),
  svg: require("@/assets/images/file/file_svg.png"),
  swift: require("@/assets/images/file/file_swift.png"),
  vue: require("@/assets/images/file/file_vue.png"),
  xml: require("@/assets/images/file/file_xml.png"),
  yaml: require("@/assets/images/file/file_yaml.png"),
  typescript: require("@/assets/images/file/file_typescript.png"),
  doc: require("@/assets/images/file/file_word.png"),
  docx: require("@/assets/images/file/file_word.png"),
  xls: require("@/assets/images/file/file_excel.png"),
  xlsx: require("@/assets/images/file/file_excel.png"),
  exe: require("@/assets/images/file/file_exe.png"),
  gif: require("@/assets/images/file/file_gif.png"),
  html: require("@/assets/images/file/file_html.png"),
  json: require("@/assets/images/file/file_json.png"),
  mp3: require("@/assets/images/file/file_music.png"),
  flac: require("@/assets/images/file/file_music.png"),
  pdf: require("@/assets/images/file/file_pdf.png"),
  ppt: require("@/assets/images/file/file_ppt.png"),
  pptx: require("@/assets/images/file/file_ppt.png"),
  txt: require("@/assets/images/file/file_txt.png"),
  zip: require("@/assets/images/file/file_zip.png"),
  wav: require("@/assets/images/file/file_music.png"),
  mp4: require("@/assets/images/file/file_avi.png"),
  jpg: require("@/assets/images/file/file_image.png"),
  png: require("@/assets/images/file/file_image.png"),
  jpeg: require("@/assets/images/file/file_image.png"),
  bmp: require("@/assets/images/file/file_image.png"),
  rpm: require("@/assets/images/file/file_rpm.png"),
  unknown: require("@/assets/images/file/file_unknown.png")
};

export function getFileIcon(fileSuffix: string): string {
  fileSuffix = fileSuffix.toLowerCase();
  return fileImgMap[fileSuffix as keyof typeof fileImgMap] || fileImgMap.unknown
}
